import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting database seed...');

  // Create common food items with nutrition data
  const foodsWithNutrition = [
    {
      name: 'Chicken Breast',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 165,
        protein: 31,
        carbs: 0,
        fat: 3.6,
        fiber: 0,
        sugar: 0,
        sodium: 74,
        cholesterol: 85,
        saturatedFat: 1,
        transFat: 0,
      },
    },
    {
      name: 'Brown Rice',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 112,
        protein: 2.6,
        carbs: 24,
        fat: 0.9,
        fiber: 1.8,
        sugar: 0.4,
        sodium: 5,
        cholesterol: 0,
        saturatedFat: 0.2,
        transFat: 0,
      },
    },
    {
      name: 'Broccoli',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 34,
        protein: 2.8,
        carbs: 7,
        fat: 0.4,
        fiber: 2.6,
        sugar: 1.7,
        sodium: 33,
        cholesterol: 0,
        saturatedFat: 0.1,
        transFat: 0,
        vitaminA: 31,
        vitaminC: 89.2,
        calcium: 47,
        iron: 0.73,
      },
    },
    {
      name: 'Eggs',
      brand: 'Generic',
      servingSize: '1',
      servingUnit: 'large',
      nutrition: {
        calories: 72,
        protein: 6.3,
        carbs: 0.4,
        fat: 4.8,
        fiber: 0,
        sugar: 0.2,
        sodium: 71,
        cholesterol: 186,
        saturatedFat: 1.6,
        transFat: 0,
        vitaminA: 80,
        calcium: 28,
        iron: 0.9,
      },
    },
    {
      name: 'Salmon',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 208,
        protein: 20,
        carbs: 0,
        fat: 13,
        fiber: 0,
        sugar: 0,
        sodium: 59,
        cholesterol: 55,
        saturatedFat: 3.1,
        transFat: 0,
      },
    },
    {
      name: 'Oatmeal',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 389,
        protein: 16.9,
        carbs: 66.3,
        fat: 6.9,
        fiber: 10.6,
        sugar: 0,
        sodium: 2,
        cholesterol: 0,
        saturatedFat: 1.2,
        transFat: 0,
        iron: 4.7,
      },
    },
    {
      name: 'Banana',
      brand: 'Generic',
      servingSize: '1',
      servingUnit: 'medium',
      nutrition: {
        calories: 105,
        protein: 1.3,
        carbs: 27,
        fat: 0.4,
        fiber: 3.1,
        sugar: 14,
        sodium: 1,
        cholesterol: 0,
        saturatedFat: 0.1,
        transFat: 0,
        vitaminC: 10.3,
      },
    },
    {
      name: 'Greek Yogurt',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fat: 0.4,
        fiber: 0,
        sugar: 3.2,
        sodium: 36,
        cholesterol: 5,
        saturatedFat: 0.1,
        transFat: 0,
        calcium: 110,
      },
    },
    {
      name: 'Almonds',
      brand: 'Generic',
      servingSize: '28',
      servingUnit: 'g',
      nutrition: {
        calories: 164,
        protein: 6,
        carbs: 6,
        fat: 14,
        fiber: 3.5,
        sugar: 1.2,
        sodium: 0,
        cholesterol: 0,
        saturatedFat: 1.1,
        transFat: 0,
        vitaminE: 7.3,
        calcium: 76,
        iron: 1,
      },
    },
    {
      name: 'Avocado',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 160,
        protein: 2,
        carbs: 8.5,
        fat: 14.7,
        fiber: 6.7,
        sugar: 0.7,
        sodium: 7,
        cholesterol: 0,
        saturatedFat: 2.1,
        transFat: 0,
        vitaminC: 10,
      },
    },
    {
      name: 'Sweet Potato',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 86,
        protein: 1.6,
        carbs: 20,
        fat: 0.1,
        fiber: 3,
        sugar: 4.2,
        sodium: 55,
        cholesterol: 0,
        saturatedFat: 0,
        transFat: 0,
        vitaminA: 709,
        vitaminC: 2.4,
      },
    },
    {
      name: 'Spinach',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 23,
        protein: 2.9,
        carbs: 3.6,
        fat: 0.4,
        fiber: 2.2,
        sugar: 0.4,
        sodium: 79,
        cholesterol: 0,
        saturatedFat: 0.1,
        transFat: 0,
        vitaminA: 469,
        vitaminC: 28,
        calcium: 99,
        iron: 2.7,
      },
    },
    {
      name: 'Quinoa',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 120,
        protein: 4.4,
        carbs: 21,
        fat: 1.9,
        fiber: 2.8,
        sugar: 0.9,
        sodium: 7,
        cholesterol: 0,
        saturatedFat: 0.2,
        transFat: 0,
        iron: 1.5,
      },
    },
    {
      name: 'Blueberries',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 57,
        protein: 0.7,
        carbs: 14,
        fat: 0.3,
        fiber: 2.4,
        sugar: 10,
        sodium: 1,
        cholesterol: 0,
        saturatedFat: 0,
        transFat: 0,
        vitaminC: 9.7,
      },
    },
    {
      name: 'Whole Wheat Bread',
      brand: 'Generic',
      servingSize: '1',
      servingUnit: 'slice',
      nutrition: {
        calories: 69,
        protein: 3.6,
        carbs: 11.6,
        fat: 0.9,
        fiber: 1.9,
        sugar: 1.4,
        sodium: 147,
        cholesterol: 0,
        saturatedFat: 0.2,
        transFat: 0,
      },
    },
    {
      name: 'Peanut Butter',
      brand: 'Generic',
      servingSize: '32',
      servingUnit: 'g',
      nutrition: {
        calories: 188,
        protein: 7.7,
        carbs: 7.7,
        fat: 16,
        fiber: 1.9,
        sugar: 3.4,
        sodium: 152,
        cholesterol: 0,
        saturatedFat: 3.3,
        transFat: 0,
      },
    },
    {
      name: 'Milk',
      brand: 'Generic',
      servingSize: '240',
      servingUnit: 'ml',
      nutrition: {
        calories: 122,
        protein: 8,
        carbs: 12,
        fat: 4.6,
        fiber: 0,
        sugar: 12,
        sodium: 107,
        cholesterol: 20,
        saturatedFat: 2.9,
        transFat: 0,
        calcium: 276,
      },
    },
    {
      name: 'Apple',
      brand: 'Generic',
      servingSize: '1',
      servingUnit: 'medium',
      nutrition: {
        calories: 95,
        protein: 0.5,
        carbs: 25,
        fat: 0.3,
        fiber: 4.4,
        sugar: 19,
        sodium: 2,
        cholesterol: 0,
        saturatedFat: 0,
        transFat: 0,
        vitaminC: 8.4,
      },
    },
    {
      name: 'Ground Beef',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 250,
        protein: 26,
        carbs: 0,
        fat: 15,
        fiber: 0,
        sugar: 0,
        sodium: 72,
        cholesterol: 88,
        saturatedFat: 6,
        transFat: 0.7,
        iron: 2.6,
      },
    },
    {
      name: 'Pasta',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 131,
        protein: 5,
        carbs: 25,
        fat: 1.1,
        fiber: 1.8,
        sugar: 0.6,
        sodium: 1,
        cholesterol: 0,
        saturatedFat: 0.2,
        transFat: 0,
      },
    },
    {
      name: 'Cheddar Cheese',
      brand: 'Generic',
      servingSize: '28',
      servingUnit: 'g',
      nutrition: {
        calories: 113,
        protein: 7,
        carbs: 0.4,
        fat: 9.3,
        fiber: 0,
        sugar: 0.1,
        sodium: 174,
        cholesterol: 28,
        saturatedFat: 5.3,
        transFat: 0.3,
        calcium: 200,
      },
    },
    {
      name: 'Orange',
      brand: 'Generic',
      servingSize: '1',
      servingUnit: 'medium',
      nutrition: {
        calories: 62,
        protein: 1.2,
        carbs: 15,
        fat: 0.2,
        fiber: 3.1,
        sugar: 12,
        sodium: 0,
        cholesterol: 0,
        saturatedFat: 0,
        transFat: 0,
        vitaminC: 70,
      },
    },
    {
      name: 'Tuna',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 132,
        protein: 28,
        carbs: 0,
        fat: 1.3,
        fiber: 0,
        sugar: 0,
        sodium: 50,
        cholesterol: 50,
        saturatedFat: 0.3,
        transFat: 0,
      },
    },
    {
      name: 'Carrots',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 41,
        protein: 0.9,
        carbs: 10,
        fat: 0.2,
        fiber: 2.8,
        sugar: 4.7,
        sodium: 69,
        cholesterol: 0,
        saturatedFat: 0,
        transFat: 0,
        vitaminA: 835,
        vitaminC: 5.9,
      },
    },
    {
      name: 'Cottage Cheese',
      brand: 'Generic',
      servingSize: '100',
      servingUnit: 'g',
      nutrition: {
        calories: 98,
        protein: 11,
        carbs: 3.4,
        fat: 4.3,
        fiber: 0,
        sugar: 2.7,
        sodium: 364,
        cholesterol: 17,
        saturatedFat: 2.7,
        transFat: 0,
        calcium: 83,
      },
    },
  ];

  console.log('Creating food items with nutrition data...');

  for (const food of foodsWithNutrition) {
    await prisma.foodItem.create({
      data: {
        name: food.name,
        brand: food.brand,
        servingSize: food.servingSize,
        servingUnit: food.servingUnit,
        isCustom: false,
        nutrition: {
          create: {
            calories: food.nutrition.calories,
            protein: food.nutrition.protein,
            carbs: food.nutrition.carbs,
            fat: food.nutrition.fat,
            fiber: food.nutrition.fiber || 0,
            sugar: food.nutrition.sugar || 0,
            sodium: food.nutrition.sodium || 0,
            cholesterol: food.nutrition.cholesterol || 0,
            saturatedFat: food.nutrition.saturatedFat || 0,
            transFat: food.nutrition.transFat || 0,
            vitaminA: food.nutrition.vitaminA,
            vitaminC: food.nutrition.vitaminC,
            calcium: food.nutrition.calcium,
            iron: food.nutrition.iron,
          },
        },
      },
    });
    console.log(`✓ Created ${food.name}`);
  }

  console.log(`\n✓ Successfully seeded ${foodsWithNutrition.length} food items`);
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
